cauchy – simulated-annealing
cauchy Function
8 statements
Source File
private function cauchy(location, scale)
Cauchy random number with specified location and scale parameters. The Cauchy distribution has heavier tails than the normal distribution, which can be useful for occasional large jumps in simulated annealing.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: location
location parameter (median)
real(kind=wp), intent(in) :: scale
scale parameter
Return Value real(kind=wp)
Calls
Called by
Source Code
   function cauchy(location, scale)
      real(wp),intent(in) :: location !! location parameter (median)
      real(wp),intent(in) :: scale    !! scale parameter
      real(wp) :: cauchy
      real(wp) :: u
      u = uniform_random_number()
      cauchy = location + scale * tan(pi * (u - 0.5_wp))
   end function cauchy
Call graph
cauchy calls uniform_random_number
perturb_variable calls cauchy
perturb_and_evaluate calls perturb_variable
sa calls perturb_and_evaluate
solve_simulated_annealing calls sa