solve_simulated_annealing – simulated-annealing
solve_simulated_annealing Subroutine
20 statements
Source File
public subroutine solve_simulated_annealing(iproblem, n, x, rt, t, vm, xopt, fopt, nacc, nfcnev, ier) bind(C, name="solve_simulated_annealing")
solve optimization problem using simulated annealing from C
Arguments
Type Intent Optional Attributes Name
integer(kind=c_intptr_t), intent(in), value :: iproblem
integer(kind=c_int), intent(in), value :: n
real(kind=c_double), intent(inout), dimension(n) :: x
real(kind=c_double), intent(in), value :: rt
real(kind=c_double), intent(inout) :: t
real(kind=c_double), intent(inout), dimension(n) :: vm
real(kind=c_double), intent(out), dimension(n) :: xopt
real(kind=c_double), intent(out) :: fopt
integer(kind=c_int), intent(out) :: nacc
integer(kind=c_int), intent(out) :: nfcnev
integer(kind=c_int), intent(out) :: ier
Calls
Source Code
    subroutine solve_simulated_annealing(iproblem, n, x, rt, t, vm, &
                                         xopt, fopt, nacc, nfcnev, ier) &
      bind(C, name="solve_simulated_annealing")
        integer(c_intptr_t), intent(in), value :: iproblem
        integer(c_int), intent(in), value :: n
        real(c_double), dimension(n), intent(inout) :: x
        real(c_double), intent(in), value :: rt
        real(c_double), intent(inout) :: t
        real(c_double), dimension(n), intent(inout) :: vm
        real(c_double), dimension(n), intent(out) :: xopt
        real(c_double), intent(out) :: fopt
        integer(c_int), intent(out) :: nacc
        integer(c_int), intent(out) :: nfcnev
        integer(c_int), intent(out) :: ier
        type(c_sa_wrapper_type), pointer :: wrapper
        call int_pointer_to_f_pointer(iproblem, wrapper)
        if (associated(wrapper)) then
            call wrapper%optimize(x=x, rt=rt, t=t, vm=vm, &
                                  xopt=xopt, fopt=fopt, nacc=nacc, &
                                  nfcnev=nfcnev, ier=ier)
        else
            error stop 'error in solve_simulated_annealing: wrapper or SA class is not associated'
        end if
    end subroutine solve_simulated_annealing
Call graph
solve_simulated_annealing calls int_pointer_to_f_pointer, sa
sa calls exprep, func, perturb_and_evaluate, print_vector, rand_init, uniform_random_number
perturb_and_evaluate calls perturb_variable
perturb_variable calls bipareto, cauchy, triangular_dist, truncated_normal, uniform
bipareto calls uniform_random_number, uniform
cauchy calls uniform_random_number
triangular_dist calls uniform_random_number
truncated_normal calls uniform, normal
uniform calls uniform_random_number
normal calls uniform_random_number