triangular_dist – simulated-annealing
triangular_dist Function
12 statements
Source File
private function triangular_dist(mode)
Triangular distribution on [0,1] with specified mode. Uses inverse transform sampling - very efficient, no rejection needed.
Note
The mode parameter should be in [0,1]. Common choices:
mode = 0.5: symmetric triangular
mode < 0.5: left-skewed
mode > 0.5: right-skewed
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: mode
mode of the distribution (should be in [0,1])
Return Value real(kind=wp)
Calls
Called by
Source Code
   function triangular_dist(mode)
      real(wp),intent(in) :: mode !! mode of the distribution (should be in [0,1])
      real(wp) :: triangular_dist
      real(wp) :: u, mode_clipped
      ! ensure mode is in [0,1]
      mode_clipped = max(0.0_wp, min(1.0_wp, mode))
      u = uniform_random_number()
      if (u < mode_clipped) then
         ! left side of triangle
         triangular_dist = sqrt(u * mode_clipped)
      else
         ! right side of triangle
         triangular_dist = 1.0_wp - sqrt((1.0_wp - u) * (1.0_wp - mode_clipped))
      end if
   end function triangular_dist
Call graph
triangular_dist calls uniform_random_number
perturb_variable calls triangular_dist
perturb_and_evaluate calls perturb_variable
sa calls perturb_and_evaluate
solve_simulated_annealing calls sa