uniform – simulated-annealing
uniform Function
6 statements
Source File
private function uniform(xl, xu)
Uniform random number on the interval [xl,xu].
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: xl
lower bound
real(kind=wp), intent(in) :: xu
upper bound
Return Value real(kind=wp)
Calls
Called by
Source Code
   function uniform(xl,xu)
      real(wp),intent(in) :: xl !! lower bound
      real(wp),intent(in) :: xu !! upper bound
      real(wp) :: uniform
      uniform = xl + (xu-xl)*uniform_random_number()
   end function uniform
Call graph
uniform calls uniform_random_number
bipareto calls uniform
perturb_variable calls uniform, bipareto, truncated_normal
truncated_normal calls uniform
perturb_and_evaluate calls perturb_variable
sa calls perturb_and_evaluate
solve_simulated_annealing calls sa